name: Build OpenWrt/uCentral images

env:
  AWS_DEFAULT_OUTPUT: json
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_BUCKET_NAME: ucentral-ap-firmware
  AWS_ACCOUNT_ID: ${{ secrets.UCENTRAL_S3_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.UCENTRAL_S3_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.UCENTRAL_S3_ACCESS_KEY_SECRET }}

on:
  push:
    branches: [ main, next, staging-* ]
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      x64_vm_image_name: ${{ steps.package_and_upload_image.outputs.x64_vm_image_name }}
    strategy:
      fail-fast: false
      matrix:
        target: ['glinet_axt1800']

    steps:
    - uses: actions/checkout@v3

    - name: Build image for ${{ matrix.target }}
      id: build
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        make -j TARGET=${{ matrix.target }}

    - name: Organize files
      run: |
        cd openwrt
        ./scripts/diffconfig.sh > bin/targets/ipq60xx/generic/diff.config
        cp .config bin/targets/ipq60xx/generic/config

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt_bin
        path: openwrt/bin
